### ISSUE TITLE
OSX run error

### ISSUE THREAD

**Issue by avidteacher** [norihiro/obs-color-monitor#15]
After installing plugin on Mac, I get the error "“obs-color-monitor.so” cannot be opened because the developer cannot be verified." when launching OBS 27.0.1     Plugin does not appear anywhere in OBS

Mac os 10.15.7
OBS Studio 27.0.1
Macbook Pro 16 2019

**Comment by norihiro** [comment]
Could you try this step to add exception for the plugin?

https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac

Currently I cannot signed the plugin since I don't have neither macOS 10.13+ nor an enrollment of Apple Developer Program, which are required to sign the binary.
