### ISSUE TITLE
Windows Defender detects trojan on 0.4.2 installers

### ISSUE THREAD

**Issue by CallenMagnuson** [norihiro/obs-color-monitor#60]
Windows Defender detects Trojan:Win32/Wacatac.H!ml when attempting to install. This does not happen on 0.4.1 or earlier.

**Comment by norihiro** [comment]
Thank you for your report. I've submitted the installer packages to Microsoft.
- https://www.microsoft.com/en-us/wdsi/submission/8dc59237-a877-4fa8-9be9-99c52aa17935
- https://www.microsoft.com/en-us/wdsi/submission/8e47f090-f677-4698-8ecf-2f99e4f70371

Since the installers are built on Github Action host as below, and SHA1 hash was left in the log as well, I believe the detection is false.
https://github.com/norihiro/obs-color-monitor/runs/7921066110?check_suite_focus=true

**Comment by norihiro** [comment]
The detection has been removed by Microsoft.
Please see these sites for details.
- https://www.microsoft.com/en-us/wdsi/submission/8dc59237-a877-4fa8-9be9-99c52aa17935
- https://www.microsoft.com/en-us/wdsi/submission/8e47f090-f677-4698-8ecf-2f99e4f70371

Someone mentioned code-sign of the file might reduce a possibility of such false detection. I'm considering the code-sign but won't do that right now since it requires annual fee and also need to consider flow of the code-sign while protecting the certificate signature.
