### ISSUE TITLE
Cant find after installing

### ISSUE THREAD

**Issue by tonybramley** [norihiro/obs-color-monitor#68]
here is the log file:
https://obsproject.com/logs/VzBKUq0LoxhRoz5d

Thanks

**Comment by norihiro** [comment]
Your CPU is Apple M2 but OBS Studio is running on Rosetta.
To solve the issue, I suggest
- Run OBS Studio without Rosetta.
  You should download OBS Studio from https://github.com/obsproject/obs-studio/releases/
- Download x86_64 version of this plugin.
  the latest obs-color-monitor so that the binary includes both x86_64 and arm64. Please go to https://github.com/norihiro/obs-color-monitor/releases/.
  Currently, 0.4.4 is the latest.
